# Generated by Django 5.0.6 on 2024-08-02 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='price_per_month',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
