# Generated by Django 5.0.6 on 2024-06-13 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='graduated',
            field=models.BooleanField(default=False),
        ),
    ]
